=== DohnalT/DohnalT-repository/XmlSchema.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="Prehravac">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="uzivatel" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Jmeno">
                                 <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                          <xs:pattern value="[a-zA-Z0-9]{0,16}"/>
                                      </xs:restriction>
                                 </xs:simpleType>
                            </xs:element>   
                            <xs:element name="Prijmeni">
                                 <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                          <xs:pattern value="[a-zA-Z0-9]{0,16}"/>
                                      </xs:restriction>
                                 </xs:simpleType>                              
                            </xs:element>  
                            <xs:element name="pocet-skladeb" type="xs:string"
                            minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="naposledy-prehrano" type="xs:string"/>
                            <xs:element name="naposledy-pridano" type="xs:string"/>
                            <xs:element name="oblibena-skladba" type="xs:string"/>                  
                         </xs:sequence>                                      
                    </xs:complexType>
                </xs:element>
                <xs:element name="vychozi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jazyk" default="CZ">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
					<xs:enumeration value="CZ"/>
					<xs:enumeration value="EN"/>
					<xs:enumeration value="DE"/>
                                        <xs:enumeration value="FR"/>
                                    </xs:restriction>
                                </xs:simpleType>                                                               
                            </xs:element>
                            <xs:element name="velikost-okna" default="720x480">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
					<xs:enumeration value="720x480"/>
					<xs:enumeration value="1920x1080"/>
					<xs:enumeration value="1280x720"/>
                                    </xs:restriction>
                                </xs:simpleType>                                                               
                            </xs:element>
                            <xs:element name="barva-pozadi" default="cerna">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
					<xs:enumeration value="bila"/>
					<xs:enumeration value="modra"/>
					<xs:enumeration value="cervena"/>
                                        <xs:enumeration value="zelena"/>
                                        <xs:enumeration value="zluta"/>
                                        <xs:enumeration value="cerna"/>
                                    </xs:restriction>
                                </xs:simpleType>                                                               
                            </xs:element>
                             <xs:element name="barva-pisma" default="bila">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
					<xs:enumeration value="bila"/>
					<xs:enumeration value="modra"/>
					<xs:enumeration value="cervena"/>
                                        <xs:enumeration value="zelena"/>
                                        <xs:enumeration value="zluta"/>
                                        <xs:enumeration value="cerna"/>
                                    </xs:restriction>
                                </xs:simpleType>                                                               
                            </xs:element>
                            <xs:element name="seradit-podle" default="data">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
					<xs:enumeration value="data"/>
					<xs:enumeration value="velikosti"/>
					<xs:enumeration value="delky"/>
                                        <xs:enumeration value="abecedy"/>
                                    </xs:restriction>
                                </xs:simpleType>                                                               
                            </xs:element>
                            <xs:element name="rozlozeni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
					<xs:enumeration value="kachle"/>
					<xs:enumeration value="ikony"/>
                                        <xs:enumeration value="sloupce"/>
                                    </xs:restriction>
                                </xs:simpleType> 
                            </xs:element>
                            <xs:element name="napoveda">
					<xs:complexType>
						<xs:attribute type="xs:boolean" name="enabled"/>
					</xs:complexType>
                            </xs:element>   
                            <xs:element name="prehravani">
                                <xs:complexType>
                                    <xs:sequence>
                                         <xs:element name="zapnout-opakovani">
                                            <xs:complexType>
						<xs:attribute type="xs:boolean" name="enabled"/>
                                            </xs:complexType>
                                         </xs:element>
                                         <xs:element name="nahodne-prehravani">
                                            <xs:complexType>
						<xs:attribute type="xs:boolean" name="enabled"/>
                                            </xs:complexType>
                                         </xs:element>
                                         <xs:element name="ztlumit">
                                            <xs:complexType>
						<xs:attribute type="xs:boolean" name="enabled"/>
                                            </xs:complexType>
                                         </xs:element>
                                         <xs:element name="hlasitost">
                                            <xs:simpleType>
                                                 <xs:restriction base="xs:nonNegativeInteger">
                                                    <xs:maxInclusive value="100"/>
                                                 </xs:restriction>
                                            </xs:simpleType>   
                                         </xs:element> 
                                         <xs:element name="vizualizer">
                                            <xs:complexType>
						<xs:attribute type="xs:boolean" name="enabled"/>
                                            </xs:complexType>
                                         </xs:element>
                                         <xs:element name="prehrat-vse">
                                            <xs:complexType>
						<xs:attribute type="xs:boolean" name="enabled"/>
                                            </xs:complexType>
                                         </xs:element>
                                         <xs:element name="promitani-fotografii">
                                            <xs:complexType>
						<xs:attribute type="xs:boolean" name="enabled"/>
                                            </xs:complexType>
                                         </xs:element> 
                                    </xs:sequence>
                                </xs:complexType>                      
                     </xs:element>
                            <xs:element name="rozsirene-nastaveni">
                                 <xs:complexType>
                                     <xs:sequence>
                                         <xs:element name="vysky">
                                                    <xs:simpleType>
							<xs:restriction base="xs:nonNegativeInteger">
								<xs:maxInclusive value="10"/>
							</xs:restriction>
                                                    </xs:simpleType>
                                         </xs:element>
                                         <xs:element name="stredy">
                                                    <xs:simpleType>
							<xs:restriction base="xs:nonNegativeInteger">
								<xs:maxInclusive value="10"/>
							</xs:restriction>
                                                    </xs:simpleType>
                                         </xs:element>
                                         <xs:element name="basy">
                                                    <xs:simpleType>
							<xs:restriction base="xs:nonNegativeInteger">
								<xs:maxInclusive value="10"/>
							</xs:restriction>
                                                    </xs:simpleType>
                                         </xs:element>
                                         <xs:element name="vyvazeni">
                                                    <xs:simpleType>
							<xs:restriction base="xs:nonNegativeInteger">
								<xs:maxInclusive value="10"/>
							</xs:restriction>
                                                    </xs:simpleType>
                                         </xs:element>
                                     </xs:sequence>
                                 </xs:complexType>
                             </xs:element>
                          </xs:sequence>
                     </xs:complexType>
                </xs:element>                                      
                                         <xs:element name="autor" maxOccurs="unbounded" minOccurs="0">
                                             <xs:complexType>
                                                 <xs:sequence>
                                                    <xs:element name="Jmeno">
                                                        <xs:simpleType>
                                                              <xs:restriction base="xs:string">
                                                                <xs:pattern value="[a-zA-Z0-9]{0,16}"/>
                                                              </xs:restriction>
                                                         </xs:simpleType>
                                                       </xs:element>   
                                                       <xs:element name="Prijmeni">
                                                         <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[a-zA-Z0-9]{0,16}"/>
                                                            </xs:restriction>
                                                         </xs:simpleType>                              
                                                       </xs:element>  
                             
                                                     <xs:element name="Vek">
                                                        <xs:simpleType>
										<xs:restriction base="xs:integer">
											<xs:minInclusive value="0"/>
											<xs:maxInclusive value="150"/>
										</xs:restriction>                    
                                                        </xs:simpleType>     
                                                    </xs:element>
                                                   <xs:element name="Datum-narozeni" type="xs:string"/>
                                                   <xs:element name="Zeme-puvodu" type="xs:string"/>
                                                   <xs:element name="oceneni" type="xs:string"/>
                                                   <xs:element name="website" type="xs:string"/>
                                                   <xs:element name="instrumenty" type="xs:string"/>
                                                   <xs:element name="aktivni-roky" type="xs:string"/>
                                                   <xs:element name="zanry" type="xs:string"/>
                                                   <xs:element name="prezdivka" type="xs:string"/>
                                                   <xs:element name="nahravaci-studio" type="xs:string"/>
                                                   <xs:element name="kapela" type="xs:string"/>
                                                   <xs:element name="clenove-kapely" type="xs:string"/>
                                                   <xs:element name="nejznamejsi-track" type="xs:string"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                                             </xs:complexType>                                         
                                           </xs:element>
              <xs:element name="hudba" maxOccurs="unbounded" minOccurs="0">
                           <xs:complexType>
                                <xs:sequence>
                                         <xs:element name="nazev" type="xs:string"/>
                                         <xs:element name="album" type="xs:string"/>
                                         <xs:element name="delka" type="xs:string"/>
                                         <xs:element type="xs:string" name="velikost-souboru"/>
                                         <xs:element name="hodnoceni">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:minInclusive value="0"/>
										<xs:maxInclusive value="5"/>
									</xs:restriction>
								</xs:simpleType>
                                         </xs:element>
                                         <xs:element name="datum-vytvoreni" type="xs:string"/>
                                         <xs:element name="datum-zmeny" type="xs:string"/>
                                         <xs:element name="zanr" type="xs:string"/>
                                         <xs:element name="cesta-ke-slozce" type="xs:string" />
                                         <xs:element name="format">
                                             <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                	<xs:enumeration value="mp3"/>
                                                        <xs:enumeration value="mp4"/>
                                                    	<xs:enumeration value="WAV"/>
                                                        <xs:enumeration value="MIDI"/>
                                                    </xs:restriction>
                                             </xs:simpleType>                                                               
                                        </xs:element>                                                   
                                </xs:sequence>
                                <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                             </xs:complexType>     
                </xs:element>
               </xs:sequence>
             </xs:complexType>
            </xs:element>
                                                                                                                                                                    

</xs:schema>

=== DohnalT/DohnalT-repository/XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<Prehravac xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XmlSchema.xsd">
 <uzivatel>
    <Jmeno>Alexandr</Jmeno>
    <Prijmeni>Veliky</Prijmeni>
    <pocet-skladeb>126</pocet-skladeb>
    <naposledy-prehrano>Zustanu-svuj</naposledy-prehrano>
    <naposledy-pridano>Byt-stale-mlad</naposledy-pridano>
    <oblibena-skladba>Bila-Orchidej</oblibena-skladba>
 </uzivatel>
 <uzivatel>
    <Jmeno>Natalie</Jmeno>
    <Prijmeni>Bila</Prijmeni>
    <pocet-skladeb>7</pocet-skladeb>
    <naposledy-prehrano>Bila-Noc</naposledy-prehrano>
    <naposledy-pridano>Haleluja</naposledy-pridano>
    <oblibena-skladba>Arakain</oblibena-skladba>
  </uzivatel>
  <vychozi>
      <jazyk>CZ</jazyk>
      <velikost-okna>720x480</velikost-okna>
      <barva-pozadi>cerna</barva-pozadi>
      <barva-pisma>bila</barva-pisma>
      <seradit-podle>data</seradit-podle>
      <rozlozeni>sloupce</rozlozeni>
      <napoveda enabled="true" />
        <prehravani>
          <zapnout-opakovani enabled = "false" />
          <nahodne-prehravani enabled= "false" />
          <ztlumit enabled= "false" />
          <hlasitost>50</hlasitost>
          <vizualizer enabled= "true" />
          <prehrat-vse enabled="true"/>
          <promitani-fotografii enabled="false"/>
        </prehravani>
        <rozsirene-nastaveni>
          <vysky>7</vysky>
          <stredy>5</stredy>
          <basy>0</basy>
          <vyvazeni>1</vyvazeni>
        </rozsirene-nastaveni>
  </vychozi>
      <autor id="1">
        <Jmeno>Petr</Jmeno>
        <Prijmeni>Vysoky</Prijmeni>
        <Vek>37</Vek>
        <Datum-narozeni>18.5.1980</Datum-narozeni>
        <Zeme-puvodu>Belgie</Zeme-puvodu>
        <oceneni>Belg-Awards</oceneni>
        <website>BelgPetr.be</website>
        <instrumenty>housle</instrumenty>
        <aktivni-roky>2000-2006</aktivni-roky>
        <zanry>country</zanry>
        <prezdivka>High-Belg</prezdivka>
        <nahravaci-studio>zadne </nahravaci-studio>
        <kapela>Petri</kapela>
        <clenove-kapely>Julius-a-Markus</clenove-kapely>
        <nejznamejsi-track>Jedu-na-Zapad</nejznamejsi-track>
      </autor>
      <autor id="2">
        <Jmeno>Adam</Jmeno>
        <Prijmeni>Maly</Prijmeni>
        <Vek>57</Vek>
        <Datum-narozeni>1.7.1960</Datum-narozeni>
        <Zeme-puvodu>Brazilie</Zeme-puvodu>
        <oceneni>Slavik</oceneni>
        <website>AMaly.br</website>
        <instrumenty>kytara</instrumenty>
        <aktivni-roky>2008-2010</aktivni-roky>
        <zanry>pop</zanry>
        <prezdivka>king</prezdivka>
        <nahravaci-studio>zadne</nahravaci-studio>
        <kapela>Jelen</kapela>
        <clenove-kapely>Eva-a-Vasek</clenove-kapely>
        <nejznamejsi-track>Vychod</nejznamejsi-track>
      </autor>
     <hudba id="3"> 
        <nazev>Poletuchy</nazev>
        <album>Nahoda</album>
        <delka>2:15</delka>
        <velikost-souboru>3200kb</velikost-souboru>
        <hodnoceni>5</hodnoceni>
        <datum-vytvoreni>10.3.2013</datum-vytvoreni>
        <datum-zmeny>15.7.2016</datum-zmeny>
        <zanr>country</zanr>
        <cesta-ke-slozce>Knihovny/Hudba</cesta-ke-slozce>
        <format>mp3</format>
      </hudba> 
      <hudba id="4"> 
        <nazev>Kalibr</nazev>
        <album>Vitr</album>
        <delka>4:05</delka>
        <velikost-souboru>4200kb</velikost-souboru>
        <hodnoceni>5</hodnoceni>
        <datum-vytvoreni>12.3.2003</datum-vytvoreni>
        <datum-zmeny>10.7.1986</datum-zmeny>
        <zanr>country</zanr>
        <cesta-ke-slozce>Knihovny/Hudba</cesta-ke-slozce>
        <format>mp3</format>
     </hudba> 
</Prehravac>
